Update release promote command in setup.sh
The --to-target parameter was added to avoid an error.

ERROR: (gcloud.beta.deploy.releases.promote) This release is not deployed to a target in the active delivery pipeline. Include the --to-target parameter to indicate which target to promote to.